services:
  - type: web
    name: gestion-de-flotte
    runtime: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/auth/login

    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES
        value: 8h
      - key: RENDER
        value: true
